version: '3.8'

services:
  # Evolution API - Stable version for WhatsApp
  evolution-api:
    image: atendai/evolution-api:v1.7.4
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      SERVER_URL: http://localhost:8080
      PORT: 8080

      # Database - Disabled for simplicity
      DATABASE_ENABLED: false

      # Authentication
      AUTHENTICATION_API_KEY: 'evolution-api-key-2024'
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: true

      # Webhook Configuration
      WEBHOOK_GLOBAL_ENABLED: true
      WEBHOOK_GLOBAL_URL: 'http://host.docker.internal:8200/webhooks/wa'
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: false

      # Storage - Disabled for simplicity
      STORE_MESSAGES: false
      STORE_MESSAGE_UP: false
      STORE_CONTACTS: false
      STORE_CHATS: false

      # Redis - Disabled
      REDIS_ENABLED: false

      # Logs
      LOG_LEVEL: INFO
      LOG_COLOR: true

    networks:
      - evolution_network

networks:
  evolution_network:
    driver: bridge