# Evolution API - Fly.io Configuration
app = "evolution-api-saas"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  SERVER_URL = "https://evolution-api-saas.fly.dev"
  PORT = "8080"
  AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES = "true"
  LOG_LEVEL = "INFO"
  LOG_COLOR = "true"
  STORE_MESSAGES = "true"
  STORE_MESSAGE_UP = "true"
  STORE_CONTACTS = "true"
  STORE_CHATS = "true"
